dist: trusty
sudo: false
language: ruby
cache:
  directories:
  - vendor/bundle

env:
  global:
  - RAILS_ENV=test
  - CC_TEST_REPORTER_ID=2862a5400e7f0cccd981d0c84f5b6518f1b7ebd0bf64a63ee0afd01abd987ed1

rvm:
  - 2.5.3

addons:
  postgresql: '9.6'

branches:
  only:
  - master

before_install:
  - gem update --system
  - gem install bundler

install:
- bundle install --path vendor/bundle
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter

before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres

script:
- bundle exec rake db:schema:load
- "./cc-test-reporter before-build"
- bundle exec rspec spec
- "./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.simplecov.json"
- "./cc-test-reporter sum-coverage coverage/codeclimate.*.json"
- "./cc-test-reporter upload-coverage"
- "./cc-test-reporter after-build"
- bundle exec bundle-audit update && bundle exec bundle-audit check

notifications:
  - false