version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 54321:5432

  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:passw0rd@db:5432/postgres
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    stdin_open: true
    tty: true
